permalink: /:year:month:day/:title
url: "https://nuke86.github.io/linuxpromo.github.io" #Your url here
baseurl: "linuxpromo.github.io/"

# variables
name: Linux.Promo
description: "Il mondo Linux italiano, fatto di Guide, articoli, suggerimenti e trucchi utili a vivere con il Pinguino"
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
